name: fitness_
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  get: ^4.6.6
  http: ^1.2.0
  flutter_staggered_animations: ^1.1.1

flutter:
  uses-material-design: true
  assets :
    - images/